version: '3'

services:
  rsshub:
    image: ghcr.io/huyyi/rsshub-reverse:latest
    ports:
      - '1200:1200'
    env_file: .env.rsshub
    environment:
      NODE_ENV: production
      CACHE_TYPE: redis
      REDIS_URL: 'redis://redis:6379/'
    depends_on:
      - redis

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis:/data

volumes:
  redis:
