services:
  freshrss-db:
    image: postgres:12-alpine
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: freshrss
      POSTGRES_PASSWORD: freshrss
      POSTGRES_DB: freshrss
  
  freshrss-app:
    image: freshrss/freshrss:latest
    ports:
      - 8080:80
    depends_on:
      - freshrss-db
    volumes:
      - data:/var/www/FreshRSS/data
    environment:
      CRON_MIN: '*/20'
      TZ: Asia/Shanghai

volumes:
  db:
  data: