# This is a basic workflow to help you get started with Actions

name: build-and-push-to-gcr
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: 
      - reverse
    paths:
      - 'lib/**'
      - '.github/workflows/build-and-push-to-gcr.yml'
      - 'Dockerfile'
      - 'package.json'
      - 'yarn.lock'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: ~

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check-env:
    runs-on: ubuntu-latest
    outputs:
      check-docker: ${{ steps.check-docker.outputs.defined }}
    steps:
      - id: check-docker
        env:
          DOCKER_USERNAME: ${{ github.repository_owner }}
        if: ${{ env.DOCKER_USERNAME != '' }}
        run: echo "::set-output name=defined::true"
        
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        buildkitd-flags: --debug

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ghcr.io/${{ github.repository_owner }}/rsshub
        tags: |
          type=raw,value=latest,enable=true
        flavor: latest=false
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64
        cache-from: type=gha,scope=docker-release
        cache-to: type=gha,mode=max,scope=docker-release
