name: deploy-on-okteto

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - master
    paths:
      - 'lib/**'
      - 'okteto*'
      - '.github/workflows/*'
  schedule:
    - cron: "30 2 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: ~

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: download
        run: |
          curl --user '${{ secrets.WEBDAV_AUTH }}' 'https://dav.jianguoyun.com/dav/GitHubAction/rsshub/.env' -o '.env.rsshub'

      - name: context
        uses: okteto/context@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}

      - name: deploy
        uses: docker://okteto/okteto
        with:
          entrypoint: okteto
          args: deploy --namespace ${{ secrets.OKTETO_NAMESPACE }} --name rsshub

  test:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: test-reverse
        shell: python
        run: |
          import time
          import sys
          import requests

          test_url = "https://rsshub-${{ secrets.OKTETO_NAMESPACE }}.cloud.okteto.net/reverse/https%3A%2F%2Fsspai.com%2Ffeed?mode=fulltext"
          for i in range(1, 11):
            print(f"test {i}/10")
            status = requests.get(test_url).status_code
            if status == 200:
              print("return 200, ok")
              sys.exit(0)
            elif status == 404:
              print("return 404, failed")
              sys.exit(1)
            else:
              print("waiting for server ready...")
              time.sleep(30)
