name: deploy-on-okteto

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: 
      - master
    paths:
      - 'lib/**'
      - 'okteto*'
      - '.github/workflows/*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: ~

jobs:
  setup-context:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      
      - name: context
        uses: okteto/context@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}
          namespace: ${{ secrets.OKTETO_NAMESPACE }}

      - name: pipeline
        uses: okteto/pipeline@latest

