name: deploy-on-okteto

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - master
    paths:
      - 'lib/**'
      - 'okteto*'
      - '.github/workflows/*'
  schedule:
    - cron: "30 2 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: ~

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: download
        run: |
          curl --user '${{ secrets.WEBDAV_AUTH }}' 'https://dav.jianguoyun.com/dav/GitHubAction/rsshub/.env' -o '.env.rsshub'

      - name: context
        uses: okteto/context@latest
        with:
          token: ${{ secrets.OKTETO_TOKEN }}

      - name: deploy
        uses: docker://okteto/okteto
        with:
          entrypoint: okteto
          args: deploy --namespace ${{ secrets.OKTETO_NAMESPACE }} --name rsshub

  test:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: test-reverse
        run: |
          curl -I "https://rsshub-${{ secrets.OKTETO_NAMESPACE }}.cloud.okteto.net/reverse/https%3A%2F%2Fsspai.com%2Ffeed?mode=fulltext" 2>/dev/null | grep 404
          [[ $? -eq 0 ]] && exit 1
